---
title: "Automatisierte Detektion von Einzelbäumen"
format: html
editor: visual
---

```{r}
#| echo: false
#| include: false

# Quarto specific - need to set the working directory to git and R project location
setwd("..")

# Source necessary codes
source("src/r/001_Initialization.R")
source("reporting/R001a_prepare_layers.R")
source("reporting/R001b_prepare_maps.R")

```

Der erste Schritt des Projekts wendet sich an der automatisierte Detektion von Einzelbäumen auf der landwirtschaftlichen Nutzfläche. Dies wird anhand der gewählten Untersuchungsgebiete getestet.

{{< include R001c_text_analysis.md >}}

### Engelswilen

```{r}
#| echo: false

tlm_eb_maps[["engelswilen"]]
```

### Prévonloup

```{r}
#| echo: false

tlm_eb_maps[["prevonloup"]]
```

### Rickenbach

```{r}
#| echo: false

tlm_eb_maps[["rickenbach"]]
```

### Orzens

```{r}
#| echo: false

tlm_eb_maps[["orzens"]]
```

### Rischberg (ALLEMA Perimeter)

```{r}
#| echo: false

tlm_eb_maps[["allema_rischberg"]]
```

### Schäfboden (ALLEMA Perimeter)

```{r}
#| echo: false

tlm_eb_maps[["allema_schafboden"]]
```
