project:
  type: book

book:
  title: Boschettissimo
  subtitle: Digitale Erkennung und Bewertung von Bäumen auf landwirtschaftlicher Nutzfläche
  repo-url: https://github.com/blw-ofag-ufag/boschettissimo
  repo-subdir: docs
  repo-actions: [source, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - aim.qmd
    - data.qmd
    - detection.qmd
    - limitations.qmd
    - references.qmd
  navbar:
    title: false
    search: true
  tools:
  - icon: envelope-fill
    href: mailto:info@blw.admin.ch

lang: de-CH

bibliography: references.bib

format:
  html:
    theme: cosmo