---
title: Datengrundlage
lang: de-CH
---

Als Datengrundlage wurden folgende vier wichtige Datensammlungen identifiziert:

## Vegetationshöhenmodell (VHM)

Ein Produkt, welches von der WSL bereitgestellt wird und anzeigt, wie hoch die Vegetation auf einer bestimmten Fläche ist.
Hat eine Auflösung von 1 × 1 m und wird alle sechs Jahre aus Luftbildern und alle sechs Jahre (um drei Jahre versetzt) aus LIDAR-Scans gerechnet.
Siehe: [Vegetationshöhenmodell LFI](https://opendata.swiss/de/dataset/vegetationshohenmodell-lfi) und [Vegetationshöhenmodell Lidar LFI](https://opendata.swiss/de/dataset/vegetationshohenmodell-lidar-lfi).

::: {#fig-vhm}
```{=html}
<iframe 
    src="https://map.geo.admin.ch/#/embed?lang=de&center=2727300,1271000&z=9&topic=ech&layers=ch.bafu.landesforstinventar-vegetationshoehenmodell_lidar@,,1"
    width="100%" 
    height="500px"
    style="border: 1pt solid black;"
    allow="geolocation" 
    allowfullscreen>
</iframe>
```
Interaktive Ansicht des Vegetationshöhenmodell Lidar LFI der Vergation rund um Weerswilen TG.
:::

## Geobasisdaten Landwirtschaftliche Kulturflächen

Die landwirtschaftlichen Geodaten basieren auf dem minimalen Geodatenmodell gemäss der Modelldokumentation "Landwirtschaftliche Kulturflächen" [@blw2026mgdm].
Dieses Modell strukturiert die landwirtschaftlichen Kulturflächen in verschiedene Informationsebenen (Layers), welche die minimalen Anforderungen an Struktur und Detaillierungsgrad für den Geodatenaustausch zwischen Bund und Kantonen definieren.
Beschrieben sind fünf Layer, wobei vier davon für dieses Projekt von Relevanz sind:

- [153.1 Nutzungsflächen](@sec-153.1)
- [153.3 Biodiversitätsförderflächen Qualitätsstufe II und Vernetzung](@sec-153.3)
- [153.5 Perimeter Landwirtschaftliche Nutzfläche und Sömmerungsflächen](@sec-153.5)
- [153.6 Bewirtschaftungseinheiten](@sec-153.6)

Diese Layers werden in den folgenden Unterkapiteln im Detail beschrieben.[^1]

[^1]: Die Reihenfolge wurde gewählt, um den Lesefluss zu verbessern und entspricht daher nicht der Reihenfolge der Identifikatoren.

### Bewirtschaftungseinheiten {#sec-153.6}

Das Modell "153.6 Bewirtschaftungseinheiten" beschreibt die Flächen, welche von einem bestimmten Betrieb (Ganzjahres- oder Sömmerungsbetrieb) zugeordnet sind Zur Identifikation des Betriebs wird die Betriebsnummer aus AGIS verwendet.
Zusätzlich beinhaltet dieser Layer die Produktionsstätten. "Als Als Produktionsstätte gilt eine Einheit von Land, Gebäuden und Einrichtungen, die räumlich als solche erkennbar und getrennt von anderen Produktionsstätten ist" [@blw2026mgdm, Seite 35].
Die Summe aller Bewirtschaftungseinheiten eines Betriebes ergibt dessen gesamte Betriebsfläche beziehungsweise den Alpperimeter im Sömmerungsgebiet.
Diese Ebene dient als räumliche Grundlage und Erfassungshilfe für die detaillierteren Nutzungsflächen.

### Perimeter Landwirtschaftliche Nutzfläche und Sömmerungsflächen {#sec-153.5}

Das Modell "153.5 Perimeter Landwirtschaftliche Nutzfläche und Sömmerungsflächen" stellt die potenziell landwirtschaftlich zu bewirtschaftende Fläche nach [Art. 14 LBV](https://www.fedlex.admin.ch/eli/cc/1999/13/de#art_14) dar.
Die Ebene dient ebenfalls als Erfassungshilfe für die Nutzungsflächen.
Der Layer stellt die potentiell landwirtschaftlich bewirtschaftbaren Flächen dar. Dabei interessiert vor allem die Abgrenzung (Perimeter) dieser 
Flächen.
Der Perimeter der Landwirtschaftliche Nutzfläche und Sömmerungsflächen wird von den Kantonen festgelegt und periodisch aktua
lisiert.
Als Grundlage zur Erstellung dieser Flächen dient primär die Bodenbedeckung der Amtlichen Vermessung.
Die Polygone in diesem Layer können Lücken oder Löcher aufweisen und decken die Schweiz nicht vollständig ab [@blw2026mgdm, Seite 15].

### Nutzungsflächen

Das Modell "153.1 Nutzungsflächen" beschreib die Nutzungsflächen selbst, also die effektiv landwirtschaftlich genutzten Flächen gemäss der Landwirtschaftlichen Begriffsverordnung (LBV) und der Direktzahlungsverordnung (DZV).
Jede Nutzungsfläche muss zwingend innerhalb einer zugeteilten Bewirtschaftungseinheit (153.6) liegen.
Die Geometrien sind als Multipolygone erfasst und mit einem spezifischen Nutzungscode (`LNF_Code`) versehen, welche die Hauptkultur auf dieser Fläche in einem bestimmten Jahr identifiziert.
Bäume können in diesem Modell zusätzlich als überlagernde Flächen geometrisch erfasst werden, wobei die Anzahl der Bäume im Attribut `Anzahl_Baeume` als Zahl angehängt wird.
Dieses Attribut ist jedoch optional und wird daher nicht von allen Kantonen erfasst.

::: {#fig-vhm}
```{=html}
<iframe 
    src="https://map.geo.admin.ch/#/embed?lang=de&center=2727300,1271000&z=9&topic=ech&layers=ch.bafu.landesforstinventar-vegetationshoehenmodell_lidar@,t,1;ch.blw.landwirtschaftliche-nutzungsflaechen@,t,0.6"
    width="100%" 
    height="500px"
    style="border: 1pt solid black;"
    allow="geolocation" 
    allowfullscreen>
</iframe>
```
Interaktive Ansicht des Vegetationshöhenmodell Lidar LFI mit darübergelegter Karte der landwirtschaftlichen Nutzungsflächen (Geobasisdaten 153.1) der Vergation rund um Weerswilen TG. Obstanlagen sind hier gut ersichtlich, da hochwachsende Vegetation innerhalb der Nutzungsflächen liegt.
:::

Für das Projekt Boschettissimo sind die Nutzungsflächen besonderes relevant, da die Direktzahlungsbeiträge auf diesen Flächen basieren.

### Biodiversitätsförderflächen Qualitätsstufe II und Vernetzung

Dieses Modell überlagert die Ebene der Nutzungsflächen und beschreibt spezifisch diejenigen Elemente, für welche Bundesbeiträge bezüglich biologischer Qualität und Vernetzung ausgerichtet werden.
Der Layer ist in zwei separate Ebenen gegliedert (Qualitätsstufe II und Vernetzung), welche sich auch gegenseitig überlagern können.
Die Flächen in diesem Modell sind grösstenteils eine Untermenge der Biodiversitätsförderflächen der Qualitätsstufe I aus dem Layer 153.1.
Ausnahmen bilden beispielsweise Hochstamm-Feldobstbäume (QII) oder artenreiche Grün- und Streueflächen im Sömmerungsgebiet.
Sie weisen keine direkte datentechnische Verknüpfung zu den Bewirtschaftungseinheiten auf; der Bezug zum Betrieb wird stattdessen durch einen räumlichen Flächenverschnitt mit den anderen Layern hergestellt.

## SWISSIMAGE

Das Orthofoto SWISSIMAGE ist eine Zusammensetzung der neuen digitalen Farbluftbilder über die ganze Schweiz mit einer Bodenauflösung von 10 cm im Flachland und den wichtigsten Alpentälern sowie 25 cm in den Alpen.
Es wird in einem Nachführungszyklus von drei Jahren seit 2018 aktualisiert, wobei jeweils um drei Jahre versetzt alle sechs Jahre Bäume belaubt und unbelaubt fotografiert werden. 

## swissSURFACE3D

Beschreibt die Oberfläche der Schweiz mit allen natürlichen und künstlichen Elementen in Form einer klassifizierten Punktwolke.
Die mit einem airborne LiDAR erhobenen Daten zeichnen sich durch eine hohe Punktdichte und Genauigkeit aus. swissSURFACE3D wird in Kacheln von jeweils 1 km^2^ produziert.
Die Kachelnummerierung entspricht den Kilometerkoor-dinaten des südwestlichen Eckpunkts einer Kachel.
