---
keywords:
  - Ergebnisorientierte Fördersysteme
  - Fernerkundung
  - Agroforstwirtschaft
  - Biodiversität
---

## Vorwort {.unnumbered}

::: {.callout-warning title="Work in Progress"}
Dieses Projekt und die vorliegende Dokumentation befinden sich derzeit in der Entwicklungsphase und werden laufend aktualisiert.

Bitte beachten Sie zudem: Bei diesem Projekt handelt es sich (nur) um eine Machbarkeitsstudie. Ob und gegebenenfalls wie die Förderung von Bäumen über Direktzahlungen künftig angepasst wird, hängt von verschiedenen Faktoren ab – unter anderem von den Ergebnissen dieser Machbarkeitsstudie.
:::

## Ziel dieses Projekts

Ziel ist die Entwicklung eines Systems, das weg von starren Massnahmenvorschriften (heutiges Direktzahlungssystem) hin zu einer ergebnisorientierten Förderung von Bäumen in der Landwirtschaft führt.
Anstatt die Pflege massnahmenorientiert vorzuschreiben, soll der effektive ökologische Wert eines Baumes mittels Fernerkundungsdaten ermittelt und vergütet werden.
Folglich sind die Kernziele des Projekts:

1. **Automatisierte Detektion** von Einzelbäumen auf der landwirtschaftlichen Nutzfläche.
2. **Merkmalsextraktion** von physischen Attributen wie Höhe, Kronenvolumen, Baumdichte.
3. **Klassifizierung** funktionaler Gruppen (z. B. Laubbaum vs. Nadelbaum, Hochstamm).
4. **Bewertung** pro Baum, also Berechnung eines "Ökologischen Nutzenwerts" als Basis für Beitragszahlungen.
5. **Ex-post-Analyse** der Berechnungen und Bewertung, um die Auswirkungen und Folgen eines möglichen Systemwechsels zu verstehen.
